version: "3.1"

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=api_rest_typescript
    ports:
      - 5432:5432
